### ISSUE TITLE
CSS - Estrutura dos Módulos

### ISSUE THREAD

**Issue by bernardodiasc** [avanteweb/avanteweb.github.io#35]
Vamos adotar uma convenção de independencia dos módulos no que se trata de estilização.

Todo o estilo dos módulos devem conter o seletor `.module.nome-do-modulo` no incio de todas as propriedades.

Ex:

``` css
.module.nome-do-modulo .titulo {
  font-size: 9em;
}

.module.nome-do-modulo a {
  color: blue;
}
```

Os estilos que forem considerados globais devem ser inseridos em `/global/styles.css`.

> Lembrando sempre de escrever `css` usando os padrões adotados para o projeto
> Mais informações em #32
